--CREATE Gold Employee Master (Now Includes Supervisor Info)

CREATE OR REPLACE DYNAMIC TABLE GOLD.EMPLOYEE_MASTER
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.EMAIL,
    E.HIRE_DATE,
    ES.TERMINATION_DATE,
    ES.EMPLOYMENT_STATUS,
    D.DEPARTMENT_NAME,
    D.LOCATION AS DEPARTMENT_LOCATION,
    E.JOB_TITLE,
    S.SUPERVISOR_NAME,
    S.SUPERVISOR_EMAIL,
    EL.WORK_LOCATION,
    DATEDIFF('DAY', E.HIRE_DATE, COALESCE(ES.TERMINATION_DATE, CURRENT_DATE())) AS TENURE_DAYS
FROM SILVER.EMPLOYEES E
LEFT JOIN SILVER.DEPARTMENTS D USING (DEPARTMENT_ID)
LEFT JOIN SILVER.SUPERVISORS S USING (SUPERVISOR_ID)
LEFT JOIN SILVER.EMPLOYEE_STATUS ES USING (EMPLOYEE_ID)
LEFT JOIN SILVER.EMPLOYEE_LOCATION EL USING (EMPLOYEE_ID);
