
--CREATE Gold Attrition Metrics

CREATE OR REPLACE DYNAMIC TABLE GOLD.ATTRITION_METRICS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DEPARTMENT_NAME,
    COUNT_IF(TERMINATION_DATE IS NOT NULL) AS TERMINATIONS,
    COUNT_IF(TERMINATION_DATE IS NULL) AS ACTIVE_EMPLOYEES,
    COUNT(*) AS TOTAL_EMPLOYEES,
    ROUND(
        COUNT_IF(TERMINATION_DATE IS NOT NULL) / NULLIF(COUNT(*), 0) * 100,
        2
    ) AS ATTRITION_RATE
FROM GOLD.EMPLOYEE_MASTER
GROUP BY DEPARTMENT_NAME;