--CREATE Gold Department Metrics

CREATE OR REPLACE DYNAMIC TABLE GOLD.DEPARTMENT_METRICS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DEPARTMENT_NAME,
    COUNT_IF(EMPLOYMENT_STATUS = 'ACTIVE') AS ACTIVE_HEADCOUNT,
    COUNT_IF(EMPLOYMENT_STATUS = 'TERMINATED') AS TERMINATED_COUNT,
    COUNT(*) AS TOTAL_EMPLOYEES
FROM GOLD.EMPLOYEE_MASTER
GROUP BY DEPARTMENT_NAME;