
--CREATE  Gold employee location master

CREATE OR REPLACE DYNAMIC TABLE GOLD.EMPLOYEE_LOCATION_MASTER
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    EL.EMPLOYEE_ID,
    EM.FIRST_NAME,
    EM.LAST_NAME,
    EL.WORK_LOCATION,
    EL.EFFECTIVE_START_DATE,
    EL.EFFECTIVE_END_DATE
FROM SILVER.EMPLOYEE_LOCATION EL
LEFT JOIN SILVER.EMPLOYEES EM
    ON EL.EMPLOYEE_ID = EM.EMPLOYEE_ID;
