
--CREATE  Gold employee status master

CREATE OR REPLACE DYNAMIC TABLE GOLD.EMPLOYEE_STATUS_MASTER
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    ES.EMPLOYEE_ID,
    EM.FIRST_NAME,
    EM.LAST_NAME,
    ES.EMPLOYMENT_STATUS,
    ES.STATUS_EFFECTIVE_DATE,
    ES.TERMINATION_DATE
FROM SILVER.EMPLOYEE_STATUS ES
LEFT JOIN SILVER.EMPLOYEES EM
    ON ES.EMPLOYEE_ID = EM.EMPLOYEE_ID;
