
--CREATE  Gold Hiring Trends

CREATE OR REPLACE DYNAMIC TABLE GOLD.HIRING_TRENDS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE_TRUNC('MONTH', HIRE_DATE) AS HIRE_MONTH,
    COUNT(*) AS HIRES
FROM GOLD.EMPLOYEE_MASTER
GROUP BY HIRE_MONTH
ORDER BY HIRE_MONTH;