--1. CREATE DATABASE WAREHOUSE

CREATE DATABASE IF NOT EXISTS HR_ANALYTICS;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = 'XSMALL';

--2 CREATE SCHEMAS
USE DATABASE HR_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;