CREATE SCHEMA IF NOT EXISTS EXPORT;
USE SCHEMA EXPORT;

------------------------------------------------------------
-- EMPLOYEE MASTER (UPDATED WITH LOCATION + STATUS)
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_EMPLOYEE_MASTER AS
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    HIRE_DATE,
    TERMINATION_DATE,
    EMPLOYMENT_STATUS,
    DEPARTMENT_NAME,
    DEPARTMENT_LOCATION,
    JOB_TITLE,
    SUPERVISOR_NAME,
    SUPERVISOR_EMAIL,
    WORK_LOCATION,
    TENURE_DAYS
FROM HR_ANALYTICS.GOLD.EMPLOYEE_MASTER;

------------------------------------------------------------
-- DEPARTMENT METRICS
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_DEPARTMENT_METRICS AS
SELECT
    DEPARTMENT_NAME,
    ACTIVE_HEADCOUNT,
    TERMINATED_COUNT,
    TOTAL_EMPLOYEES
FROM HR_ANALYTICS.GOLD.DEPARTMENT_METRICS;

------------------------------------------------------------
-- ATTRITION METRICS
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_ATTRITION_METRICS AS
SELECT
    DEPARTMENT_NAME,
    TERMINATIONS,
    TOTAL_EMPLOYEES,
    ATTRITION_RATE
FROM HR_ANALYTICS.GOLD.ATTRITION_METRICS;

------------------------------------------------------------
-- HIRING TRENDS
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_HIRING_TRENDS AS
SELECT
    HIRE_MONTH,
    HIRES
FROM HR_ANALYTICS.GOLD.HIRING_TRENDS;

------------------------------------------------------------
-- EMPLOYEE LOCATION MASTER (NEW)
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_EMPLOYEE_LOCATION_MASTER AS
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    WORK_LOCATION,
    EFFECTIVE_START_DATE,
    EFFECTIVE_END_DATE
FROM HR_ANALYTICS.GOLD.EMPLOYEE_LOCATION_MASTER;

------------------------------------------------------------
-- EMPLOYEE STATUS MASTER (NEW)
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_EMPLOYEE_STATUS_MASTER AS
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMPLOYMENT_STATUS,
    STATUS_EFFECTIVE_DATE,
    TERMINATION_DATE
FROM HR_ANALYTICS.GOLD.EMPLOYEE_STATUS_MASTER;

------------------------------------------------------------
-- COMBINED CONTEXT VIEW (UPDATED)
------------------------------------------------------------
CREATE OR REPLACE VIEW EXPORT.V_EMPLOYEE_DEPARTMENT_CONTEXT AS
SELECT
    EM.EMPLOYEE_ID,
    EM.FIRST_NAME,
    EM.LAST_NAME,
    EM.EMAIL,
    EM.HIRE_DATE,
    EM.TERMINATION_DATE,
    EM.EMPLOYMENT_STATUS,
    EM.DEPARTMENT_NAME,
    EM.DEPARTMENT_LOCATION,
    EM.JOB_TITLE,
    EM.SUPERVISOR_NAME,
    EM.SUPERVISOR_EMAIL,
    EM.WORK_LOCATION,
    EM.TENURE_DAYS,
    DM.ACTIVE_HEADCOUNT,
    DM.TERMINATED_COUNT,
    DM.TOTAL_EMPLOYEES,
    AM.ATTRITION_RATE
FROM HR_ANALYTICS.GOLD.EMPLOYEE_MASTER EM
LEFT JOIN HR_ANALYTICS.GOLD.DEPARTMENT_METRICS DM
    ON EM.DEPARTMENT_NAME = DM.DEPARTMENT_NAME
LEFT JOIN HR_ANALYTICS.GOLD.ATTRITION_METRICS AM
    ON EM.DEPARTMENT_NAME = AM.DEPARTMENT_NAME;
