-- CREATE SILVER LAYER DYNAMIC TABLES

CREATE OR REPLACE DYNAMIC TABLE SILVER.EMPLOYEES
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    EMPLOYEE_ID,
    INITCAP(FIRST_NAME) AS FIRST_NAME,
    INITCAP(LAST_NAME) AS LAST_NAME,
    LOWER(EMAIL) AS EMAIL,
    HIRE_DATE,
    TERMINATION_DATE,
    DEPARTMENT_ID,
    INITCAP(JOB_TITLE) AS JOB_TITLE,
    INITCAP(LOCATION) AS LOCATION,
    UPPER(STATUS) AS STATUS,
    SUPERVISOR_ID
FROM BRONZE.EMPLOYEES_RAW;

CREATE OR REPLACE DYNAMIC TABLE SILVER.DEPARTMENTS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DEPARTMENT_ID,
    INITCAP(DEPARTMENT_NAME) AS DEPARTMENT_NAME,
    INITCAP(LOCATION) AS LOCATION
FROM BRONZE.DEPARTMENTS_RAW;

CREATE OR REPLACE DYNAMIC TABLE SILVER.JOB_HISTORY
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    EMPLOYEE_ID,
    INITCAP(JOB_TITLE) AS JOB_TITLE,
    START_DATE,
    END_DATE
FROM BRONZE.JOB_HISTORY_RAW;


CREATE OR REPLACE DYNAMIC TABLE SILVER.SUPERVISORS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SUPERVISOR_ID,
    INITCAP(SUPERVISOR_NAME) AS SUPERVISOR_NAME,
    LOWER(SUPERVISOR_EMAIL) AS SUPERVISOR_EMAIL,
    DEPARTMENT_ID
FROM BRONZE.SUPERVISORS_RAW;

CREATE OR REPLACE DYNAMIC TABLE SILVER.EMPLOYEE_STATUS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    EMPLOYEE_ID,
    EMPLOYMENT_STATUS,
    STATUS_EFFECTIVE_DATE,
    TERMINATION_DATE
FROM BRONZE.EMPLOYEE_STATUS_RAW;


CREATE OR REPLACE DYNAMIC TABLE SILVER.EMPLOYEE_LOCATION
TARGET_LAG = '5 MINUTES'
WAREHOUSE = COMPUTE_WH
AS
SELECT
    EMPLOYEE_ID,
    WORK_LOCATION,
    EFFECTIVE_START_DATE,
    EFFECTIVE_END_DATE
FROM BRONZE.EMPLOYEE_LOCATION_RAW;
