-- CREATE BRONZE LAYER RAW TABLES

CREATE OR REPLACE TABLE BRONZE.EMPLOYEES_RAW (
    EMPLOYEE_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    HIRE_DATE DATE,
    TERMINATION_DATE DATE,
    DEPARTMENT_ID NUMBER,
    JOB_TITLE STRING,
    LOCATION STRING,
    STATUS STRING,
    SUPERVISOR_ID NUMBER
);

CREATE OR REPLACE TABLE BRONZE.DEPARTMENTS_RAW (
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME STRING,
    LOCATION STRING
);


CREATE OR REPLACE TABLE BRONZE.JOB_HISTORY_RAW (
    EMPLOYEE_ID NUMBER,
    JOB_TITLE STRING,
    START_DATE DATE,
    END_DATE DATE
);

CREATE OR REPLACE TABLE BRONZE.SUPERVISORS_RAW (
    SUPERVISOR_ID NUMBER,
    SUPERVISOR_NAME STRING,
    SUPERVISOR_EMAIL STRING,
    DEPARTMENT_ID NUMBER
);

CREATE OR REPLACE TABLE BRONZE.EMPLOYEE_STATUS_RAW (
    EMPLOYEE_ID NUMBER,
    EMPLOYMENT_STATUS STRING,
    STATUS_EFFECTIVE_DATE DATE,
    TERMINATION_DATE DATE
);

CREATE OR REPLACE TABLE BRONZE.EMPLOYEE_LOCATION_RAW (
    EMPLOYEE_ID NUMBER,
    WORK_LOCATION STRING,
    EFFECTIVE_START_DATE DATE,
    EFFECTIVE_END_DATE DATE
);